/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CircleLoader: typeof import('./src/components/common/loader/CircleLoader.vue')['default']
    CommonButton: typeof import('./src/components/common/button/CommonButton.vue')['default']
    ConfirmModal: typeof import('./src/components/common/modal/ConfirmModal.vue')['default']
    CustomerDataTable: typeof import('./src/components/customer/CustomerDataTable.vue')['default']
    CustomerForm: typeof import('./src/components/customer/CustomerForm.vue')['default']
    FilterCustomer: typeof import('./src/components/customer/FilterCustomer.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    Modal: typeof import('./src/components/common/modal/Modal.vue')['default']
    Pagination: typeof import('./src/components/common/pagination/Pagination.vue')['default']
    ProgressLoader: typeof import('./src/components/common/loader/ProgressLoader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Tag: typeof import('./src/components/tag/Tag.vue')['default']
    TagFilter: typeof import('./src/components/tag/TagFilter.vue')['default']
    ToastMessage: typeof import('./src/components/common/toast/ToastMessage.vue')['default']
  }
}
